apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: hello-teste
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello-teste
    newTag: 90cbf4d2d73410032ee83c2fd779e81976d2bb9c
