apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - analysistemplate.yaml
images:
  - name: hello-teste
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello-teste
    newTag: 83b6b1a21610c5941004bcbaa8dc249c026063f0
