apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - analysistemplate.yaml
images:
  - name: hello
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello
    newTag: 75e1430005ba4965a7bf80c85cd3f29badcbe25a
