apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: hello
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello
    newTag: 7b6f10f37118879b7561f3f83d2c42244f666e51
