apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: hello
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello
    newTag: b3f69ecc2850dcb5dd905f2e3d8f9f7b8be04f1a
