apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - analysistemplate.yaml
images:
  - name: hello-canary
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello-canary
    newTag: 25f1259ce180e01e8b7207254e15807bff529e17
