apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter-crd
    targetRevision: 1.13.0
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.13.0
    helm:
      values: |
        crds:
          install: false
        settings:
          clusterName: hello-observability-prod
        serviceAccount:
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::207131866724:role/hello-observability-prod-karpenter-controller
        replicas: 1
        controller:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/betodalas/hello-eks-observability.git
    targetRevision: main
    path: gitops/tools/karpenter/nodepool
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
