apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - analysistemplate.yaml
images:
  - name: hello-roberto
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello-roberto
    newTag: ed86713edd2c3a232928a85886c00b4e040d76ec
