apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - analysistemplate.yaml
images:
  - name: hello-roberto
    newName: 207131866724.dkr.ecr.us-east-1.amazonaws.com/hello-observability-prod/hello-roberto
    newTag: 70573cc06ff0d4a3556af5f2bec337d0bb6d43ba
