apiVersion: v1
kind: Secret
metadata:
  name: karpenter-oci
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: karpenter
  type: helm
  url: public.ecr.aws/karpenter
  enableOCI: "true"
